// start of FETCH PIZZAS
export const FETCH_PIZZAS_START = 'FETCH_PIZZAS_START'
export const FETCH_PIZZAS_SUCCESS = 'FETCH_PIZZAS_SUCCESS'
export const FETCH_PIZZAS_FAIL = 'FETCH_PIZZAS_FAIL'
// end of FETCH PIZZAS

// start of PIZZA EDIT FORM
export const PIZZA_EDIT_FORM_WAS_CHANGED = 'PIZZA_EDIT_FORM_WAS_CHANGED'
// end of PIZZA EDIT FORM
