// start of FETCH PIZZAS
export const FETCH_PIZZAS_START = 'FETCH_PIZZAS_START'
export const FETCH_PIZZAS_SUCCESS = 'FETCH_PIZZAS_SUCCESS'
export const FETCH_PIZZAS_FAIL = 'FETCH_PIZZAS_FAIL'
// end of FETCH PIZZAS

// start of PIZZA EDIT FORM
export const PIZZA_EDIT_FORM_WAS_CHANGED = 'PIZZA_EDIT_FORM_WAS_CHANGED'
// end of PIZZA EDIT FORM

// start of EDIT PIZZA
export const EDIT_PIZZA_START = 'EDIT_PIZZA_START'
export const EDIT_PIZZA_SUCCESS = 'EDIT_PIZZA_SUCCESS'
export const EDIT_PIZZA_FAIL = 'EDIT_PIZZA_FAIL'
// end of EDIT PIZZA

// start of ADD PIZZA
export const ADD_PIZZA_START = 'ADD_PIZZA_START'
export const ADD_PIZZA_SUCCESS = 'ADD_PIZZA_SUCCESS'
export const ADD_PIZZA_FAIL = 'ADD_PIZZA_FAIL'
// end of ADD PIZZA
